<?php

class Version20180101150001
{
    public function up(Schema $schema)
    {
    }
    public function down(Schema $schema)
    {
    }
    public function preUp(Schema $schema)
    {
    }
    public function postUp(Schema $schema)
    {
    }
    public function preDown(Schema $schema)
    {
    }
    public function postDown(Schema $schema)
    {
    }
    public function getDescription()
    {
    }
    public function isTransactional()
    {
    }
}
-----
<?php

class Version20180101150001
{
    public function up(Schema $schema): void
    {
    }
    public function down(Schema $schema): void
    {
    }
    public function preUp(Schema $schema): void
    {
    }
    public function postUp(Schema $schema): void
    {
    }
    public function preDown(Schema $schema): void
    {
    }
    public function postDown(Schema $schema): void
    {
    }
    public function getDescription(): string
    {
    }
    public function isTransactional(): bool
    {
    }
}
